#spring.application.name=E-comerc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce7
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
application:
  security:
    jwt:
      secret-key: 9fcc1d43ceb668bfe0dcff2326951b3a40034f8ee85bc32bef1555c925342d3733d840c8af268475128c22da2eae66d83d72c95d700c80f78e275f886fe2fcde
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days